site_name: Arcube Integration Guide
theme:
  name: material

nav:
  - Home: index.md
  - Integration Methods:
      - iFrame Integration: integration-methods/iframe.md
      - Email Integration: integration-methods/email.md
      - White-Label Website: integration-methods/white-label.md
      - API Integration: integration-methods/api.md
  - Integration Details:
      - Overview: integration-details/overview.md
      - Essential API Calls: integration-details/essential-api-calls.md
      - Widget Integration: integration-details/widget-integration.md
      - Email Integration: integration-details/email-integration.md
      - White-Label Integration: integration-details/white-label-integration.md
      - API Integration: integration-details/api-integration.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

