site_name: Arcube Integration Guide
site_url: https://arcube-org.github.io/arcube-integration-guide/
theme:
  name: material

nav:
  - Home: index.md
  - Product Overview: product-overview.md
  - Tenant Dashboard and Arcube Platform: arcube-platforms.md
  - Integration Methods Outline:
      - Widget Integration: integration-methods/widget.md
      - Email Integration: integration-methods/email.md
      - API Integration: integration-methods/api.md
      - (POS) White-Label Website: integration-methods/white-label.md
  - Technical & Integration Details:
      - Overview: integration-details/overview.md
      - Essential API Calls: integration-details/essential-api-calls.md
      - Widget Integration: integration-details/widget-integration.md
      - Email Integration: integration-details/email-integration.md
      - API Integration: integration-details/api-integration.md
      - (POS) White-Label Integration: integration-details/white-label-integration.md
      - API Versioning: integration-details/api-versioning.md
      - Scalability & Security: integration-details/scalability-security.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

